SystemOrganization addCategory: #BabelSt!
SystemOrganization addCategory: #'BabelSt-AST'!
SystemOrganization addCategory: #'BabelSt-Converter'!
SystemOrganization addCategory: #'BabelSt-Importer'!
SystemOrganization addCategory: #'BabelSt-Operator'!
SystemOrganization addCategory: #'BabelSt-StdClass'!
SystemOrganization addCategory: #'BabelSt-Tool'!
SystemOrganization addCategory: #'BabelSt-Visitor'!
