Class {
	#name : #BabelUnaryOperator,
	#superclass : #Object,
	#category : 'BabelSt-Operator'
}

{ #category : #'as yet unclassified' }
BabelUnaryOperator class >> DELETE [
 ^ 'delete'
]

{ #category : #'as yet unclassified' }
BabelUnaryOperator class >> EXCLAM [
 ^ '!'
]

{ #category : #'as yet unclassified' }
BabelUnaryOperator class >> MINUS [
 ^ '-'
]

{ #category : #'as yet unclassified' }
BabelUnaryOperator class >> PLUS [
 ^ '+'
]

{ #category : #'as yet unclassified' }
BabelUnaryOperator class >> TILDE [
 ^ '~'
]

{ #category : #'as yet unclassified' }
BabelUnaryOperator class >> TYPEOF [
 ^ 'typeof'
]

{ #category : #'as yet unclassified' }
BabelUnaryOperator class >> VOID [
 ^ 'void'
]
