Class {
	#name : #BabelBinaryOperator,
	#superclass : #Object,
	#category : 'BabelSt-Operator'
}

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> AMPERSAND [
	^ '&'
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> CIRCUMFLEX [
	^ '^'
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> DOUBLE_EQUAL [
	^ '=='
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> DOUBLE_INF [
	^ '<<'
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> DOUBLE_SUP [
	^ '>>'
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> EXCLAM_DOUBLE_EQUAL [
	^ '!=='
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> EXCLAM_EQUAL [
	^ '!='
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> IN [
	^ 'in'
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> INF [
	^ '<'
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> INF_EQUAL [
	^ '<='
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> INSTANCEOF [
	^ 'instanceof'
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> MINUS [
	^ '-'
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> PERCENT [
	^ '%'
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> PIPE [
	^ '|'
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> PLUS [
	^ '+'
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> SLASH [
	^ '/'
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> STAR [
	^ '*'
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> SUP [
	^ '>'
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> SUP_EQUAL [
	^ '>='
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> TRIPLE_EQUAL [
	^ '==='
]

{ #category : #'as yet unclassified' }
BabelBinaryOperator class >> TRIPLE_SUP [
	^ '>>>'
]
