Class {
	#name : #BabelAssignmentOperator,
	#superclass : #Object,
	#category : 'BabelSt-Operator'
}

{ #category : #'as yet unclassified' }
BabelAssignmentOperator class >> AMPERSAND_EQUAL [
	^ '&='
]

{ #category : #'as yet unclassified' }
BabelAssignmentOperator class >> CIRCUMFLEX_EQUAL [
	^ '^='
]

{ #category : #'as yet unclassified' }
BabelAssignmentOperator class >> DOUBLE_INF_EQUAL [
	^ '<<='
]

{ #category : #'as yet unclassified' }
BabelAssignmentOperator class >> DOUBLE_SUP_EQUAL [
	^ '>>='
]

{ #category : #'as yet unclassified' }
BabelAssignmentOperator class >> EQUAL [
	^ '='
]

{ #category : #'as yet unclassified' }
BabelAssignmentOperator class >> MINUS_EQUAL [
	^ '-='
]

{ #category : #'as yet unclassified' }
BabelAssignmentOperator class >> PERCENT_EQUAL [
	^ '%='
]

{ #category : #'as yet unclassified' }
BabelAssignmentOperator class >> PIPE_EQUAL [
	^ '|='
]

{ #category : #'as yet unclassified' }
BabelAssignmentOperator class >> PLUS_EQUAL [
	^ '+='
]

{ #category : #'as yet unclassified' }
BabelAssignmentOperator class >> SLASH_EQUAL [
	^ '/='
]

{ #category : #'as yet unclassified' }
BabelAssignmentOperator class >> STAR_EQUAL [
	^ '*='
]

{ #category : #'as yet unclassified' }
BabelAssignmentOperator class >> TRIPLE_SUP_EQUAL [
	^ '>>>='
]
